language: node_js
node_js:
  - 'node'
  - '10'
  - '8'
cache:
  directories:
    - ~/.npm

before_install:
  - npm install -g npm
  - npm install -g greenkeeper-lockfile@1
install:
  - travis_retry npm install
before_script:
  - greenkeeper-lockfile-update
after_script:
  # Only the first job will upload the lockfile
  - greenkeeper-lockfile-upload
after_success:
  - 'cat ./coverage/lcov.info | ./node_modules/.bin/coveralls'
jobs:
  include:
    - stage: release
      node_js: lts/*
      before_install:
        - npm install -g npm
      install:
        - travis_retry npm install
      before_script: skip
      script: npm run semantic-release
      after_success: skip
      after_failure: skip
      after_script: skip
